/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchUploadProgress: typeof import('./../../components/BatchUploadProgress.vue')['default']
    BloodPressureCard: typeof import('./../../components/BloodPressureCard.vue')['default']
    ConfirmHost: typeof import('./../../components/ui/ConfirmHost.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    HotkeyTooltip: typeof import('./../../components/HotkeyTooltip.vue')['default']
    LinkLoadingView: typeof import('./../../components/LinkLoadingView.vue')['default']
    ModernFontView: typeof import('./../../components/ModernFontView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastHost: typeof import('./../../components/ui/ToastHost.vue')['default']
    UiButton: typeof import('./../../components/ui/UiButton.vue')['default']
    UiCard: typeof import('./../../components/ui/UiCard.vue')['default']
    UiIcon: typeof import('./../../components/ui/UiIcon.vue')['default']
    UiInput: typeof import('./../../components/ui/UiInput.vue')['default']
    UiLogo: typeof import('./../../components/ui/UiLogo.vue')['default']
    UpdateChip: typeof import('./../../components/UpdateChip.vue')['default']
    UpdateDialog: typeof import('./../../components/UpdateDialog.vue')['default']
    VideoView: typeof import('./../../components/video/VideoView.vue')['default']
    WindowControls: typeof import('./../../components/WindowControls.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
